# Generated by Django 5.2.5 on 2025-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='barter_available',
            new_name='is_barter_available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='credit_available',
            new_name='is_credit_available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delivery_available',
            new_name='is_delivery_available',
        ),
        migrations.AddField(
            model_name='product',
            name='is_mediator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_product_new',
            field=models.BooleanField(default=False),
        ),
    ]
