# Generated by Django 5.2.5 on 2025-09-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
        ('users', '0002_remove_user_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('promoted', 'Promoted'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16, null=True),
        ),
    ]
