# Generated by Django 5.2.4 on 2025-09-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_owner_product_status_product_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean')], default='string', max_length=50),
        ),
    ]
