# Generated by Django 5.2.5 on 2025-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_store_alter_product_promotion_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('promoted', 'Promoted'), ('super_opportunity', 'Super Opportunity'), ('premium', 'Premium'), ('vip', 'VIP')], default='basic', max_length=20),
        ),
    ]
